-   id: reorder-python-imports
    name: Reorder python imports
    description: This hook reorders imports in python files.
    entry: reorder-python-imports
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
