-   id: add-noqa-imports
    name: Add noqa imports
    description: This hook adds noqa to imports that can't be made shorter due to a long path.
    entry: add-noqa-to-imports
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
